#Device default login/password
bot_access_token: "ODhiZTA2N2QtYTM2NS00NjUwLTgxNjItZmMxNTkwY2EzMDA2NzRkMWFiOGEtNDU4_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"

db_host: "10.81.127.149"
db_login: "ciscolive"
db_password: "cisco.123"

pictures_folder: "pictures/"
# Number of tasks per user
tasks_num: 3