#Device default login/password
bot_access_token: "MDI4OWQzMWItZTUyOS00MWRlLWE1NDUtNzk4MDNiOTJmMDc2NjczYzliZmEtZDg1_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
webhook_name: "webhook_quiz_cl"

db_host: "localhost"
db_login: "ciscolive"
db_password: "cisco.123"

pictures_folder: "pictures/"
# Number of tasks per user
tasks_num: 7